(function(){
'use strict';
const e=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
const meaningful=r=>r&&typeof r==='object'&&Object.values(r).some(v=>String(v??'').trim()&&!['0','0%','None','N/A'].includes(String(v).trim()));
let corReportCycleOverride='';
const corReportCycles=['Weekly','Biweekly PTR','Monthly'];
function effectiveCorReportCycle(meta){return corReportCycleOverride||String((meta||{}).reportType||'Weekly');}
function monthlyTrackerRecordIsOpen(r){const status=String((r||{}).Status||'').trim().toLowerCase();return meaningful(r)&&!['closed','complete','completed','cancelled','canceled'].includes(status);}
function monthlyCostNarrative(d){const records=(Array.isArray(d.projectRegister)?d.projectRegister:[]).filter(monthlyTrackerRecordIsOpen);const cost=records.filter(r=>{const cycle=String(r['Report Cycle']||'').trim().toLowerCase(),category=String(r.Category||'').trim().toLowerCase(),type=String(r['Record Type']||'').trim().toLowerCase(),section=String(r['Report Section']||'').trim().toLowerCase();return cycle==='monthly'&&(category==='cost'||type.includes('pay application')||section.includes('cost')||section.includes('contract administration'));}).slice(0,5);if(!cost.length)return 'No active monthly pay-application or cost-control record is currently flagged in the Project Register.';return cost.map(r=>{const title=String(r.Title||r['Record ID']||'Cost item').trim(),status=String(r.Status||'Open').trim(),action=String(r['Decision / Action Needed']||'').trim(),rec=String(r['GCC Recommendation']||'').trim();return `${title} — ${status}${action?`. ${action}`:''}${rec?` Recommendation: ${rec}`:''}`;}).join(' ');}
function monthlyNextFocus(d,look){const records=(Array.isArray(d.projectRegister)?d.projectRegister:[]).filter(monthlyTrackerRecordIsOpen);const focus=records.filter(r=>String(r['Look-Ahead Item']||'').trim().toLowerCase()==='yes'||String(r['Report Cycle']||'').trim().toLowerCase()==='monthly').sort((a,b)=>(Number(a['Look-Ahead Sequence'])||999)-(Number(b['Look-Ahead Sequence'])||999)).slice(0,6).map(r=>String(r['Decision / Action Needed']||r.Title||'').trim()).filter(Boolean);if(focus.length)return `Next-month priorities: ${focus.join('; ')}.`;return String((look||{}).lookAhead||'No next-month action is currently flagged in the Project Register.').trim();}
function monthlyTrackerHtml(d,m){const sections=Array.isArray(d.sections)?d.sections:[];const find=id=>sections.find(s=>String(s.id)===String(id))||{};const count=s=>(Array.isArray(s.rows)?s.rows:[]).filter(meaningful).length+(Array.isArray(s.operational)?s.operational:[]).filter(meaningful).length;const schedule=find('4'),quality=find('6'),accept=find('7'),look=find('9');return `<section class="cor-monthly"><h3>Monthly Project Tracker</h3><div class="cor-table-wrap"><table class="cor-table"><tbody><tr><th>Reporting Period</th><td>${e(m.periodStart||'')} – ${e(m.periodEnd||'')}</td></tr><tr><th>Progress / Accomplishments</th><td>${e(m.executiveSummary||'No executive summary is available.')}</td></tr><tr><th>Schedule / Phasing</th><td>${e(m.contractorSchedule||'Pending')} · ${count(schedule)} schedule/shutdown item${count(schedule)===1?'':'s'} tracked.</td></tr><tr><th>Pay Application / Cost</th><td>${e(monthlyCostNarrative(d))}</td></tr><tr><th>Quality / Field Status</th><td>${count(quality)} quality/readiness item${count(quality)===1?'':'s'} and ${count(accept)} OIT/commissioning/acceptance item${count(accept)===1?'':'s'} tracked.</td></tr><tr><th>Risks / Decisions</th><td>${(Array.isArray(d.decisions)?d.decisions:[]).filter(meaningful).length} COR decision${(Array.isArray(d.decisions)?d.decisions:[]).filter(meaningful).length===1?'':'s'} currently flagged.</td></tr><tr><th>Next-Month Focus</th><td>${e(monthlyNextFocus(d,look))}</td></tr></tbody></table></div></section>`;}
function table(rows){rows=Array.isArray(rows)?rows:[];if(!rows.length)return '<div class="cor-empty">No reportable records in this section.</div>';const keys=[...new Set(rows.flatMap(r=>Object.keys(r||{})))].filter(k=>rows.some(r=>String((r||{})[k]??'').trim())).slice(0,9);return `<div class="cor-table-wrap"><table class="cor-table"><thead><tr>${keys.map(k=>`<th>${e(k)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${keys.map(k=>`<td>${e((r||{})[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function sectionDetails(s,match){const rows=(Array.isArray(s.rows)?s.rows:[]).filter(match).filter(meaningful);const op=(Array.isArray(s.operational)?s.operational:[]).filter(match).filter(meaningful);const count=rows.length+op.length;return `<details class="cor-section" data-cor-section="${e(s.id)}"><summary class="cor-section-head"><span>${e(s.id)}</span><div class="cor-section-title"><h3>${e(s.title)}</h3><small>${count} reportable item${count===1?'':'s'} · Source: ${e(s.source||'PMIS')}</small></div><i class="cor-chevron" aria-hidden="true"></i></summary><div class="cor-section-body">${table(rows)}${op.length?`<div class="cor-subhead">Shutdown Tracker / Operational Records</div>${table(op)}`:''}${s.lookAhead?`<div class="cor-lookahead">${e(s.lookAhead)}</div>`:''}</div></details>`;}
window.toggleAllCorSections=open=>document.querySelectorAll('#corReportsContent details.cor-section, #corReportsContent details.cor-summary').forEach(d=>d.open=!!open);
window.renderCorReports=function(){const ds=window.data||window.PMIS_DATA||{};const d=(ds.corReports&&typeof ds.corReports==='object')?ds.corReports:{meta:{},sections:[],actions:[],decisions:[]};const m=d.meta||{},cycle=effectiveCorReportCycle(m),host=document.getElementById('corReportsContent');if(!host)throw new Error('COR Reports content container not found.');const prior=(document.getElementById('corBuildingFilter')||{}).value||'ALL';const norm=v=>{const x=String(v??'').trim().replace(/^B/i,'');return /^\d+$/.test(x)?x.padStart(2,'0'):x.toUpperCase();};const match=r=>prior==='ALL'||String((r||{}).Building||(r||{})['Building / Area']||'').toUpperCase()==='ALL'||norm((r||{}).Building||(r||{})['Building / Area'])===norm(prior);const sections=(Array.isArray(d.sections)?d.sections:[]).map(s=>sectionDetails(s,match)).join('');const stats=ds.stats||{},buildings=Array.isArray(ds.buildings)?ds.buildings:[],avg=Number(stats.avgReadiness||0),avgPct=avg>1?avg:avg*100;host.innerHTML=`<div class="cor-controls"><label>Report Cycle <select id="corReportCycle">${corReportCycles.map(x=>`<option value="${e(x)}" ${x===cycle?'selected':''}>${e(x)}</option>`).join('')}</select></label><label>Building <select id="corBuildingFilter"><option value="ALL">Campus-wide</option>${buildings.map(b=>`<option value="${e(b.Building)}">Building ${e(b.Building)}</option>`).join('')}</select></label><div class="cor-section-tools"><button type="button" onclick="toggleAllCorSections(true)">Expand all</button><button type="button" onclick="toggleAllCorSections(false)">Collapse all</button></div><div class="cor-meta">${e(cycle)} · ${e(m.projectPhase||'Project Status')} · Schedule: ${e(m.contractorSchedule||'Pending')}</div></div><div class="cor-kpis"><div><span>Buildings</span><strong>${stats.total||buildings.length||0}</strong></div><div><span>Readiness</span><strong>${Math.round(avgPct)}%</strong></div><div><span>Open Risks</span><strong>${stats.risks||0}</strong></div><div><span>Active Shutdowns</span><strong>${(Array.isArray(d.shutdowns)?d.shutdowns:[]).filter(meaningful).length}</strong></div><div><span>COR Decisions</span><strong>${(Array.isArray(d.decisions)?d.decisions:[]).filter(meaningful).length}</strong></div></div><details class="cor-summary"><summary><h3>Executive Summary</h3><i class="cor-chevron" aria-hidden="true"></i></summary><p>${e(m.executiveSummary||'No executive summary is available.')}</p></details>${cycle==='Monthly'?monthlyTrackerHtml(d,m):''}${sections||'<div class="cor-empty">The COR report data did not load.</div>'}`;const sel=document.getElementById('corBuildingFilter');if(sel){sel.value=prior;sel.addEventListener('change',window.renderCorReports);}const cyc=document.getElementById('corReportCycle');if(cyc){cyc.value=cycle;cyc.addEventListener('change',()=>{corReportCycleOverride=cyc.value;window.renderCorReports();});}};
window.copyCorDigest=async function(){const d=((window.data||window.PMIS_DATA||{}).corReports)||{},m=d.meta||{};const txt=[`COR Project Status Report — 518-22-700`,m.executiveSummary||'',...(Array.isArray(d.sections)?d.sections:[]).map(s=>`\n${s.id}. ${s.title}\n${(Array.isArray(s.rows)?s.rows:[]).filter(meaningful).slice(0,20).map(r=>Object.entries(r).filter(x=>String(x[1]??'').trim()).map(x=>`${x[0]}: ${x[1]}`).join(' | ')).join('\n')}`)].join('\n');try{await navigator.clipboard.writeText(txt);}catch(_){}};
function corPrintableTable(rows){
  rows=(Array.isArray(rows)?rows:[]).filter(meaningful);
  if(!rows.length)return '<div class="empty">No reportable records are currently listed.</div>';
  const keys=[...new Set(rows.flatMap(r=>Object.keys(r||{})))].filter(k=>rows.some(r=>String((r||{})[k]??'').trim())).slice(0,9);
  return `<table><thead><tr>${keys.map(k=>`<th>${e(k)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${keys.map(k=>`<td>${e((r||{})[k])}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
}
window.printCorReport=function(){
  const ds=window.data||window.PMIS_DATA||{};
  const d=(ds.corReports&&typeof ds.corReports==='object')?ds.corReports:{meta:{},sections:[]};
  const m=d.meta||{}, cycle=effectiveCorReportCycle(m);
  const filter=(document.getElementById('corBuildingFilter')||{}).value||'ALL';
  const norm=v=>{const x=String(v??'').trim().replace(/^B/i,'');return /^\d+$/.test(x)?x.padStart(2,'0'):x.toUpperCase();};
  const match=r=>filter==='ALL'||String((r||{}).Building||(r||{})['Building / Area']||'').toUpperCase()==='ALL'||norm((r||{}).Building||(r||{})['Building / Area'])===norm(filter);
  const stats=ds.stats||{}, buildings=Array.isArray(ds.buildings)?ds.buildings:[], avg=Number(stats.avgReadiness||0), avgPct=avg>1?avg:avg*100;
  const sections=(Array.isArray(d.sections)?d.sections:[]).map((s,i)=>{
    const rows=(Array.isArray(s.rows)?s.rows:[]).filter(match).filter(meaningful);
    const operational=(Array.isArray(s.operational)?s.operational:[]).filter(match).filter(meaningful);
    if(!rows.length&&!operational.length&&!String(s.lookAhead||'').trim()) return '';
    return `<section class="section${i>4?' page-break':''}"><h2>${e(s.id)}. ${e(s.title)}</h2><div class="status-line">Source: ${e(s.source||'PMIS')} · ${rows.length+operational.length} reportable item${rows.length+operational.length===1?'':'s'}</div>${corPrintableTable(rows)}${operational.length?`<h3>Shutdown / Operational Coordination</h3>${corPrintableTable(operational)}`:''}${s.lookAhead?`<div class="friendly-note"><b>Look-ahead:</b> ${e(s.lookAhead)}</div>`:''}</section>`;
  }).filter(Boolean).join('');
  const scope=filter==='ALL'?'Campus-wide':`Building ${filter}`;
  const body=`<div class="status-line">Reporting scope: <b>${e(scope)}</b> · ${e(cycle)} · ${e(m.projectPhase||'Project Status')}</div><div class="friendly-note">${e(m.executiveSummary||'No executive summary is currently available.')}</div><div class="kpis"><div class="kpi"><span>Buildings</span><b>${stats.total||buildings.length||0}</b></div><div class="kpi"><span>Readiness</span><b>${Math.round(avgPct)}%</b></div><div class="kpi"><span>Open Risks</span><b>${stats.risks||0}</b></div><div class="kpi"><span>Active Shutdowns</span><b>${(Array.isArray(d.shutdowns)?d.shutdowns:[]).filter(meaningful).length}</b></div></div>${cycle==='Monthly'?monthlyTrackerHtml(d,m):''}${sections||'<div class="empty">No reportable records are available for this scope.</div>'}`;
  if(typeof window.printHtmlDocument==='function') window.printHtmlDocument(`${cycle} COR Project Status Report`,body,{reportType:`${cycle} COR Project Status Report`});
  else window.print();
};
})();
